---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/resin-io/sshproxy
    docker:
      - image: golang:1.10.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make dep
      - run:
          name: Lint Code
          command: make lint
      - run:
          name: Run Tests
          command: make test
      - run:
          name: Build Releases
          command: make -j release
      - deploy:
          name: Upload Releases
          command: if git describe --exact-match --tags 2>/dev/null; then make upload; fi
